### PR TITLE
compatible with gym>=0.24.1 && fix bug

### PR DESCRIPTION
**Pull request by liyc-ai**
I mainly fix the environment.py to make it compatible with the latest version of gym (0.24.1), see more details in 'Files changed'

### CODE REVIEW

**Comment by thomashirtz** [comment]
Thank you for the contribution !
Can I know what was the compatibility issue before I accept the MR ?

**Comment by BepfCp** [comment]
> Thank you for the contribution ! Can I know what was the compatibility issue before I accept the MR ?

Thank you for your reply. The compatibility issue are mainly caused by gym's own passive_env_checker.py. Below is one compatibility issue when running gym_hybird on gym==0.24.1.
image

But I am not sure whether it is a bug of gym, because this compatibility issue is gone when upgrading gym to 0.25.0.

**Comment by thomashirtz** [comment]
I would like to first try to not use numpy array everywhere, if it doesn't pass the compatibility check with simple list, we may change it to numpy arrays as you did.

For the distance, since we are searching the hypotenuse, we have a²+b²=c², so I am not sure why you added `(2*np.sqrt(2))`

Nice catch for the import of the time as well as the order of the observation's limits :)

**Comment by BepfCp** [comment]
> I would like to first try to not use numpy array everywhere, if it doesn't pass the compatibility check with simple list, we may change it to numpy arrays as you did.
> 
> For the distance, since we are searching the hypotenuse, we have a²+b²=c², so I am not sure why you added `(2*np.sqrt(2))`
> 
> Nice catch for the import of the time as well as the order of the observation's limits :)

Sorry for my late reply. I added (2*np.sqrt(2)) to make the distance into [0, 1], also due the compatibility issue.

**Pull request closed without merging**
